# Generated by Django 3.0.6 on 2020-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_visitor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='user_id',
            field=models.CharField(blank=True, max_length=15, verbose_name='User ID'),
        ),
    ]
