# Generated by Django 3.0.6 on 2020-08-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200808_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(verbose_name='Diamonds')),
                ('price', models.FloatField(verbose_name='Harga')),
            ],
        ),
        migrations.AddField(
            model_name='visitor',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Item', verbose_name=''),
        ),
    ]
