# Generated by Django 3.0.6 on 2020-08-10 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200809_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='item',
        ),
    ]
