# Generated by Django 3.0 on 2020-10-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_carouselimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimg',
            name='img',
            field=models.ImageField(upload_to='carousel img/', verbose_name='Carousel Images'),
        ),
    ]
